name: Deploy to GitHub Pages
on:
  # 姣忔鎺ㄩ€佸埌 `main` 鍒嗘敮鏃惰Е鍙戣繖涓€滃伐浣滄祦绋嬧€?  # 濡傛灉浣犱娇鐢ㄤ簡鍒殑鍒嗘敮鍚嶏紝璇锋寜闇€灏?`main` 鏇挎崲鎴愪綘鐨勫垎鏀悕
  push:
    branches: [ main ]
  # 鍏佽浣犲湪 GitHub 涓婄殑 Actions 鏍囩涓墜鍔ㄨЕ鍙戞鈥滃伐浣滄祦绋嬧€?  workflow_dispatch:
# 鍏佽 job 鍏嬮殕 repo 骞跺垱寤轰竴涓?page deployment
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          node-version: 22
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4